sonar.projectKey=products-frontend
sonar.projectName=Products Frontend
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.test.ts,src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=src/vendor/**,public/**
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:8070
sonar.login=${SONAR_TOKEN}